backend:
  name: github
  repo: tet434950-droid/novel-scrolls-nest
  branch: main
  base_url: /.netlify/functions/decap-auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "novels"
    label: "Novels"
    folder: "data/novels"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
